/*  Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 *  By starting with 1 and 2, the first 10 terms will be:
 *
 *  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 *  Author: willtamura
 *  Date: 3/19/16
 */

#include <stdio.h>

#define LIM 4000000

int main() {
    
    int t1, t2, n, sum;
    
    // Declare first two terms
    t1 = 1;
    t2 = 2;
    
    sum = 2;
    for(n = t1+t2; n <= LIM; n = t1+t2) {
        // If even
        if(n % 2 == 0) {
            sum += n;
        }
        
        // Update terms
        t1 = t2;
        t2 = n;
    }
    printf("Sum of Even Fibonacci Numbers up to 4 Million: %d\n", sum);
    
    return 0;
}